package dev.kostromdan.mods.crash_assistant.common_config.scripts.script_utils;

import dev.kostromdan.mods.crash_assistant.common_config.mod_list.Mod;
import dev.kostromdan.mods.crash_assistant.common_config.lang.LanguageProvider;
import dev.kostromdan.mods.crash_assistant.common_config.lang.LinksProvider;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a warning generated by scripts.
 * Acts as a DTO (Data Transfer Object) to be converted into KnownCrashReason in the App module.
 */
public class ScriptWarning {
    private final String message;
    
    // Configuration
    private int priority = 10000;
    private String dontShowAgainKey = null;
    private String dontShowAgainCheckboxText = null;
    private int okDelay = 0; // seconds

    // Mod Actions
    private Mod affectedMod = null;
    private boolean showRemoveButton = true;
    private boolean showDisableButton = true;
    private boolean showExplorerButton = true;
    private boolean showKillMinecraftButton = false;
    private boolean showModListDiffButton = false;
    private List<String[]> guideButtons = new ArrayList<>();

    public ScriptWarning(String message) {
        this.message = message;
    }

    // --- Fluent API ---

    public ScriptWarning withPriority(int priority) {
        this.priority = priority;
        return this;
    }

    public ScriptWarning withDontShowAgain(String configKey) {
        this.dontShowAgainKey = configKey;
        return this;
    }

    public ScriptWarning withCustomDontShowAgainCheckboxText(String checkboxText) {
        this.dontShowAgainCheckboxText = checkboxText;
        return this;
    }

    public ScriptWarning withOkDelay(int seconds) {
        this.okDelay = seconds;
        return this;
    }

    /**
     * Enables standard mod management buttons (Remove, Disable, Show in Explorer)
     * for the specified mod.
     * The OK/Close button is always present.
     */
    public ScriptWarning withModActions(Mod mod) {
        this.affectedMod = mod;
        return this;
    }
    
    // Granular control
    public ScriptWarning withRemoveButton(boolean enable) {
        this.showRemoveButton = enable;
        return this;
    }
    
    public ScriptWarning withDisableButton(boolean enable) {
        this.showDisableButton = enable;
        return this;
    }
    
    public ScriptWarning withExplorerButton(boolean enable) {
        this.showExplorerButton = enable;
        return this;
    }

    public ScriptWarning withKillMinecraftButton(boolean enable) {
        this.showKillMinecraftButton = enable;
        return this;
    }

    public ScriptWarning withShowModListDiffButton() {
        this.showModListDiffButton = true;
        return this;
    }

    public ScriptWarning addGuideButton(String buttonText, String url) {
        this.guideButtons.add(new String[]{buttonText, url});
        return this;
    }

    public ScriptWarning withMemoryAllocationGuide() {
        return addGuideButton(LanguageProvider.get("gui.guide.memory_allocation"),
                LinksProvider.RAM_ALLOCATION_GUIDE.getLink());
    }

    public ScriptWarning withJvmArgsGuide() {
        return addGuideButton(LanguageProvider.get("gui.guide.jvm_args"),
                LinksProvider.JVM_ARGS_GUIDE.getLink());
    }

    public ScriptWarning withJavaVersionGuide() {
        return addGuideButton(LanguageProvider.get("gui.guide.java_version"),
                LinksProvider.JAVA_VERSION_GUIDE.getLink());
    }

    // --- Getters ---

    public String getMessage() {
        return message;
    }

    public int getPriority() {
        return priority;
    }

    public String getDontShowAgainKey() {
        return dontShowAgainKey;
    }

    public String getDontShowAgainCheckboxText() {
        return dontShowAgainCheckboxText;
    }

    public int getOkDelay() {
        return okDelay;
    }

    public Mod getAffectedMod() {
        return affectedMod;
    }

    public boolean isShowRemoveButton() {
        return showRemoveButton;
    }
    
    public boolean isShowDisableButton() {
        return showDisableButton;
    }
    
    public boolean isShowExplorerButton() {
        return showExplorerButton;
    }

    public boolean isShowKillMinecraftButton() {
        return showKillMinecraftButton;
    }

    public boolean isShowModListDiffButton() {
        return showModListDiffButton;
    }

    public List<String[]> getGuideButtons() {
        if (guideButtons == null) {
            guideButtons = new ArrayList<>();
        }
        return guideButtons;
    }
}
