plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'dev.kostromdan.mods'
version = ''

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://repo.lwjgl.org/'
    }
}

def lwjglVersion = '3.1.0'
def lwjglNatives = {
    def osName = System.getProperty('os.name').toLowerCase()
    if (osName.contains('win')) {
        return 'natives-windows'
    } else if (osName.contains('mac')) {
        return 'natives-macos'
    } else if (osName.contains('nix') || osName.contains('nux') || osName.contains('aix')) {
        return 'natives-linux'
    } else {
        throw new GradleException('Unsupported operating system')
    }
}()

dependencies {
    implementation 'com.formdev:flatlaf:3.7'
    implementation("org.apache.commons:commons-jexl3:3.6.2")
    implementation 'org.apache.logging.log4j:log4j-core:2.24.2'
    implementation 'org.apache.logging.log4j:log4j-api:2.24.2'
    implementation 'com.electronwill.night-config:toml:3.6.4'
    implementation 'com.electronwill.night-config:json:3.6.4'
    implementation 'commons-io:commons-io:2.15.1'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'net.java.dev.jna:jna:4.4.0'
    implementation 'net.java.dev.jna:platform:3.4.0'

    implementation "org.lwjgl:lwjgl:$lwjglVersion"
    runtimeOnly "org.lwjgl:lwjgl:$lwjglVersion:$lwjglNatives"
    implementation "org.lwjgl:lwjgl-vulkan:$lwjglVersion"

    implementation project(path: ':common_config')
}

jar {
    manifest {
        attributes(
                'Main-Class': 'dev.kostromdan.mods.crash_assistant.app.class_loading.Boot',
                'Enable-Native-Access': 'ALL-UNNAMED' // Java 22+ prevents warnings and upcoming JNI restrictions in Java 25+
        )
    }
}

shadowJar {
    from("$rootDir/LICENSE.md") {
        rename { "CRASH_ASSISTANT_LICENSE.md" }
        into ""
    }
    from("$rootDir/thirdparty") {
        into "thirdparty"
    }

    dependsOn(':common_config:build')
    archiveClassifier.set('')

    // Relocate Night Config packages
    relocate 'com.electronwill.nightconfig', 'dev.kostromdan.mods.crash_assistant.nightconfig'
    relocate 'org.apache.commons.jexl3', 'dev.kostromdan.mods.crash_assistant.commons.jexl3'
    relocate 'org.apache.commons.logging', 'dev.kostromdan.mods.crash_assistant.commons.logging'

    dependencies {
        exclude(dependency('org.apache.logging.log4j:.*'))
        exclude(dependency('com.google.code.gson:.*'))
        exclude(dependency('commons-io:commons-io:2.15.1'))
        exclude(dependency('com.electronwill.night-config:.*'))
        exclude(dependency('org.apache.commons:commons-jexl3:.*'))
        exclude(dependency('commons-logging:commons-logging:.*'))
        exclude(dependency('net.java.dev.jna:.*'))
        exclude(dependency('org.lwjgl:.*'))
        exclude(project(':common_config'))
        exclude("META-INF/LICENSE")
    }
}

build.finalizedBy(shadowJar)
